title: Dr. Christian Wilkinson
description: Postdoctoral Researcher at Observatoire de Paris | Exoplanet Modeling & Machine Learning
google_analytics: # Add your ID here if you have one
theme: jekyll-theme-architect # Or your preferred theme

# Professional Links
linkedin_username: christian-s-wilkinson
github_username: christianswilkinson

remote_theme: pages-themes/architect@v0.2.0 # Or your chosen theme
custom_css: assets/css/style.scss
